name: UPE CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libpthread-stubs0-dev pkg-config

      - name: Mock libdpdk workaround for CI
        run: |
          mkdir -p ./mock_pkgconfig

          cat << 'EOF' > ./mock_pkgconfig/libdpdk.pc
          prefix=/usr
          exec_prefix=${prefix}
          libdir=${exec_prefix}/lib
          includedir=${prefix}/include

          Name: libdpdk
          Description: Dummy DPDK so CI doesn't fail
          Version: 23.11.0
          Libs: -L${libdir}
          Cflags: -I${includedir}
          EOF

          echo "PKG_CONFIG_PATH=${{ github.workspace }}/mock_pkgconfig:$PKG_CONFIG_PATH" >> $GITHUB_ENV

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Run Unit Tests
        run: |
          cd build
          ctest -L Unit --output-on-failure

      - name: Run Benchmarks
        run: |
          cd build
          ctest -L Bench --output-on-failure